name: Build a Docker Image

# Decide the trigger when we push code to master branch

on:
  push:
    branches:
      - main
      - master

# Define the jobs
jobs:
   builds:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@v2
         
         - name: Checkout repository
           uses: docker/setup-buildx-action@v1
           
         - name: Checkout repository
           run: docker build -t my-app-image .